### ISSUE TITLE
BUG:当整数为0或-1时，都会转换成补码11111111

### ISSUE THREAD

**Issue by good1uck** [leizelong/binary#1]
补码的表示是唯一的，对于0补码只有一种表示，即00000000

**Comment by leizelong** [comment]
好的，我修复一下。

**Comment by leizelong** [comment]
[
![image](https://user-images.githubusercontent.com/30491515/72229574-ae3bde80-35ea-11ea-80d5-2429ec3e937d.png)
](url)

**Comment by leizelong** [comment]
测试结果是符合预期的。
